// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htmvkmxeicqzzwhdwdub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bXZrbXhlaWNxenp3aGR3ZHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzMwNjYsImV4cCI6MjA2MDIwOTA2Nn0.44H7WYISCDy22B0gQDs7Cr2omzrEIbW9gG1xc3-5GXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);